import { Booking, ActiveJobRequest, ServiceItem, WorkerProfile } from './types';

export const INITIAL_SERVICES: ServiceItem[] = [
  {
    id: 'elec-1',
    name: 'Electrician',
    category: 'Electrical',
    baseRatePerHour: 200,
    rating: 4.89,
    jobsCount: 340,
    badge: 'Verified',
    description: 'Wiring, repairs, MCB, switchboard installations',
    iconName: 'bolt',
    popular: true,
  },
  {
    id: 'plumb-1',
    name: 'Plumber',
    category: 'Plumbing',
    baseRatePerHour: 250,
    rating: 4.92,
    jobsCount: 520,
    badge: 'Fair Match',
    description: 'Pipe leaks, taps, sanitary fittings, tank overhaul',
    iconName: 'water_drop',
    popular: true,
  },
  {
    id: 'carp-1',
    name: 'Carpenter',
    category: 'Carpentry',
    baseRatePerHour: 250,
    rating: 4.85,
    jobsCount: 280,
    badge: 'Verified',
    description: 'Furniture assembly, doors, locks & wood polish',
    iconName: 'carpenter',
  },
  {
    id: 'paint-1',
    name: 'Painter',
    category: 'Painting',
    baseRatePerHour: 300,
    rating: 4.78,
    jobsCount: 190,
    badge: 'Verified',
    description: 'Interior, exterior wall painting & waterproofing touchup',
    iconName: 'format_paint',
  },
  {
    id: 'app-1',
    name: 'Appliance Repair',
    category: 'Appliances',
    baseRatePerHour: 350,
    rating: 4.91,
    jobsCount: 410,
    badge: 'Fair Match',
    description: 'AC service, washing machine, geyser & microwave fix',
    iconName: 'kitchen',
  },
  {
    id: 'clean-1',
    name: 'Home Cleaning & Pest',
    category: 'Cleaning',
    baseRatePerHour: 400,
    rating: 4.87,
    jobsCount: 370,
    badge: 'Verified',
    description: 'Deep cleaning, kitchen degreasing & organic pest care',
    iconName: 'cleaning_services',
  },
];

export const WORKER_RAVI: WorkerProfile = {
  id: 'w-ravi-01',
  name: 'Ravi Kumar',
  title: 'Licensed Electrician & Plumber',
  phone: '+91 98480 23145',
  email: 'ravi.electrician.undi@gmail.com',
  rating: 4.92,
  reviewsCount: 430,
  experienceYears: 7,
  jobsCompleted: 482,
  onTimePercent: 98,
  hourlyRate: 250,
  avatarUrl: 'https://images.unsplash.com/photo-1540569014015-19a7be504e3a?w=240&auto=format&fit=crop&q=80',
  qualifications: ['SSC & ITI Verified', 'Co-op Shield Insured', 'Trade Master Grade A'],
  languages: ['Telugu', 'English', 'Hindi'],
  mandal: 'Undi Mandal',
  cluster: 'Undi Cluster, West Godavari',
  shareholderId: '#408',
  education: {
    level: '10th Standard / SSC Passed',
    school: 'Zilla Parishad High School, Undi (BSEA)',
    rollNo: 'SSC-2015-84920',
    passYear: '2015',
  },
  kyc: {
    aadhaarMasked: '•••• 4892 (UIDAI Biometric Verified)',
    upiId: 'ravi.undi@sbi',
  },
};

export const WORKER_SURESH: WorkerProfile = {
  id: 'w-suresh-02',
  name: 'Suresh Varma',
  title: 'Senior Certified Electrician',
  phone: '+91 97011 44520',
  email: 'suresh.varma@coworkseva.in',
  rating: 4.8,
  reviewsCount: 290,
  experienceYears: 6,
  jobsCompleted: 312,
  onTimePercent: 96,
  hourlyRate: 250,
  avatarUrl: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=240&auto=format&fit=crop&q=80',
  qualifications: ['10th Pass Verified', 'Wireman License #882'],
  languages: ['Telugu', 'English'],
  mandal: 'Bhimavaram',
  cluster: 'Bhimavaram Town Co-op',
  shareholderId: '#512',
  education: {
    level: '10th Standard (SSC)',
    school: 'Govt High School, Bhimavaram',
    rollNo: 'SSC-2016-11029',
    passYear: '2016',
  },
  kyc: {
    aadhaarMasked: '•••• 7712 (UIDAI Biometric Verified)',
    upiId: 'suresh.varma@ybl',
  },
};

export const INITIAL_BOOKINGS: Booking[] = [
  {
    id: 'CWS-8492',
    serviceId: 'plumb-1',
    serviceName: 'Plumbing Repair',
    category: 'Plumbing',
    status: 'in-progress',
    dateStr: 'Today, 05 Sep',
    timeWindow: '2:00 PM - 4:00 PM',
    workerCount: 1,
    durationHours: 2,
    assignedWorkers: [WORKER_RAVI],
    customerName: 'Harsha Vardhan',
    customerPhone: '+91 98765 43210',
    address: '42 Cooperative Way, Block B, Flat 302, Green Park, Undi, 534199',
    landmark: 'Near Undi Panchayati Library',
    problemDescription: 'Kitchen washbasin lower elbow leaking water continuously.',
    ratePerHour: 250,
    totalAmount: 500,
    paidAmount: 500,
    paymentMethod: 'UPI',
    paymentStatus: 'paid',
    stepCurrent: 2,
    arrivingMinutes: 12,
  },
  {
    id: 'CWS-7910',
    serviceId: 'elec-1',
    serviceName: 'Electrical Switchboard Installation',
    category: 'Electrical',
    status: 'completed',
    dateStr: '28 Aug 2024',
    timeWindow: '11:00 AM - 12:30 PM',
    workerCount: 1,
    durationHours: 1.5,
    assignedWorkers: [WORKER_SURESH],
    customerName: 'Harsha Vardhan',
    customerPhone: '+91 98765 43210',
    address: '42 Cooperative Way, Block B, Flat 302, Green Park, Undi',
    problemDescription: 'Installed 2 modern modular boards with surge arrestor.',
    ratePerHour: 250,
    totalAmount: 375,
    paidAmount: 375,
    paymentMethod: 'UPI',
    paymentStatus: 'paid',
    completedDate: '28 Aug 2024',
    ratingGiven: 5,
    reviewComment: 'Very clean wiring work and tested every socket with load meter.',
  },
  {
    id: 'CWS-6214',
    serviceId: 'carp-1',
    serviceName: 'Carpenter - Bed Repair & Wood Polish',
    category: 'Carpentry',
    status: 'completed',
    dateStr: '14 Aug 2024',
    timeWindow: '10:00 AM - 1:00 PM',
    workerCount: 1,
    durationHours: 3,
    assignedWorkers: [
      {
        ...WORKER_RAVI,
        id: 'w-venkat-03',
        name: 'Venkat Rao',
        title: 'Master Carpenter',
        rating: 5.0,
        hourlyRate: 250,
        avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=240&auto=format&fit=crop&q=80',
      },
    ],
    customerName: 'Harsha Vardhan',
    customerPhone: '+91 98765 43210',
    address: '42 Cooperative Way, Block B, Flat 302, Green Park, Undi',
    problemDescription: 'Strengthened teak bed frame support & natural polish.',
    ratePerHour: 250,
    totalAmount: 750,
    paidAmount: 750,
    paymentMethod: 'Cash',
    paymentStatus: 'paid',
    completedDate: '14 Aug 2024',
    ratingGiven: 5,
  },
  {
    id: 'CWS-5102',
    serviceId: 'elec-1',
    serviceName: 'Ceiling Fan & Geyser Service',
    category: 'Electrical',
    status: 'completed',
    dateStr: '02 Jul 2024',
    timeWindow: '3:00 PM - 5:00 PM',
    workerCount: 1,
    durationHours: 2,
    assignedWorkers: [
      {
        ...WORKER_RAVI,
        id: 'w-naidu-04',
        name: 'M. Naidu',
        title: 'Electrical & Appliance Technician',
        rating: 4.7,
        hourlyRate: 200,
        avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=240&auto=format&fit=crop&q=80',
      },
    ],
    customerName: 'Harsha Vardhan',
    customerPhone: '+91 98765 43210',
    address: '42 Cooperative Way, Block B, Flat 302, Green Park, Undi',
    problemDescription: 'Replaced fan bearing and cleaned geyser heating element.',
    ratePerHour: 200,
    totalAmount: 400,
    paidAmount: 400,
    paymentMethod: 'UPI',
    paymentStatus: 'paid',
    completedDate: '02 Jul 2024',
    ratingGiven: 5,
  },
];

export const INITIAL_ACTIVE_JOBS: ActiveJobRequest[] = [
  {
    id: 'job-req-01',
    customerName: 'Venkata Lakshmi',
    customerAvatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=160&auto=format&fit=crop&q=80',
    distanceKm: 1.2,
    locationArea: 'Undi Main Road',
    trade: 'Electrician',
    title: 'Ceiling Fan Sparking & Short Circuit Repair',
    description: '"Master bedroom fan started making clicking noise and sparking when turned to speed 3. Need urgent inspection."',
    rate: 300,
    timing: '< 30 mins',
    isUrgent: true,
    status: 'pending',
    timeNotice: 'URGENT • JUST NOW',
    slotType: 'urgent',
  },
  {
    id: 'job-req-02',
    customerName: 'Suresh Reddy',
    customerAvatar: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=160&auto=format&fit=crop&q=80',
    distanceKm: 3.8,
    locationArea: 'Rayalam Road',
    trade: 'Plumbing',
    title: 'Water Tank Float Valve & Pipe Leakage',
    description: '"Overhead tank overflow valve broken, leaking onto roof slab."',
    rate: 450,
    timing: 'Today, 4:00 - 6:00 PM',
    isUrgent: false,
    status: 'pending',
    timeNotice: 'Today, 4:00 - 6:00 PM',
    slotType: 'today',
  },
  {
    id: 'job-req-03',
    customerName: 'Anusha G.',
    customerAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=160&auto=format&fit=crop&q=80',
    distanceKm: 2.5,
    locationArea: 'Green Park colony',
    trade: 'Electrical',
    title: 'Full House Switchboard Upgrade',
    description: 'Complete replacement of 6 switchboards with modular fittings. Materials provided by customer.',
    rate: 900,
    timing: 'Tomorrow, 10:00 AM',
    isUrgent: false,
    status: 'pending',
    timeNotice: 'Tomorrow, 10:00 AM',
    slotType: 'tomorrow',
  },
];

export const SAMPLE_ACTIVE_BOOKING: Booking = INITIAL_BOOKINGS[0];
